In [1]:
# Install pandas in the new environment

import pandas as pd

# Create a dataframe with numeric and text columns
df = pd.DataFrame({
    "Character": ["Aragorn", "Boromir", "Frodo", "Galadriel"],
    "Base_Age": [88, 41, 51, 8382]
})
df

   Character  Base_Age
0    Aragorn        88
1    Boromir        41
2      Frodo        51
3  Galadriel      8382

In [2]:
import pandas as pd

# Step 5: Create your dataframe
df = pd.DataFrame({
    "Character": ["Aragorn", "Boromir", "Frodo", "Galadriel"],
    "Base_Age": [88, 41, 51, 8382]
})

# Step 6: Lambda Mathematical Procedure (e.g., divide age by 10)
df['Valinor_Age'] = df['Base_Age'].apply(lambda x: x / 10)

# Step 7: Lambda Flag Column (e.g., label as 'Hobbit' or 'Other')
df['Race_Flag'] = df['Character'].apply(lambda x: 'Hobbit' if x == 'Frodo' else 'Other')

# Display the result
df

   Character  Base_Age  Valinor_Age Race_Flag
0    Aragorn        88          8.8     Other
1    Boromir        41          4.1     Other
2      Frodo        51          5.1    Hobbit
3  Galadriel      8382        838.2     Other